### ISSUE TITLE
Digest title prediction invalid

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/digestclub#70]
It seems that on some digest title prediction the model is failing and we should handle it better

![image](https://github.com/premieroctet/digestclub/assets/686101/6594f33d-a97d-4c61-a355-d1c2c815c109)

**Comment by mrnossiom** [comment]
LMAO, nice one.
I was about to open an issue about the order given to the digests when asking for completion.

![image](https://github.com/premieroctet/digestclub/assets/43814157/dd854f51-5ebd-46fb-8179-c7ff5e4a7150)

My guess is that July is given due to the order of the issues. GPT tries to output the next logical month, which in this logical order is July.

Issues could be ordered by ascending date before asking GPT.
